### ISSUE TITLE
v0.1.0 Checklist

### ISSUE THREAD

**Issue by jaredcnance** [Research-Institute/json-api-dotnet-core#1]
- Middleware should check whether or not the route has been configured, create the controller instance, call the specified method:
  - [x] GET /{namespace}/{entities}/
  - [x] GET /{namespace}/{entities}/{id}
  - [x] POST /{namespace}/{entities}/
  - [x] PATCH /{namespace}/{entities}/{id}
  - [x] DELETE /{namespace}/{entities}/{id}
- Support Relationship Links:
  - [x] "self": "http://example.com/articles/1/relationships/author"
  - [x] "related": "http://example.com/articles/1/author"
- [x] Check to see if there is a controller override specified (interface vs. abstract vs. concrete controller), if so call the override methods instead
- [x] Convert entities to JsonApiDocuments
- [x] Convert JsonApiDocuments to entities
- [x] End the request pipeline
- [x] Consider using AutoMapper to map from the model to a JsonApiResource
- [x] CI build setup
- [x] #3 : Resource mapping
- [x] #9 : Querying Records
